server:
  port: 8088 #端口号
spring:
  application:
    name: yyms-service-wechat
  servlet:
    context-path: /wx
  datasource: #数据源
    druid:
      url: jdbc:mysql://39.108.217.158:3306/leanin_follow?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
wx:
  appId:  wx1f020aa42d92b635
  appSecret: 21be49689399a4e8eb437c371f42fbab
