<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://service.patient.manager.leanin.com" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://service.leanin.com" name="TestWebServiceWs" targetNamespace="http://service.patient.manager.leanin.com">
  <wsdl:import location="http://192.168.0.131:8082/soap/test?wsdl=TestWebServiceWs.wsdl" namespace="http://service.leanin.com">
    </wsdl:import>
  <wsdl:binding name="TestWebServiceWsSoapBinding" type="ns1:TestWebServiceWs">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="testWS">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="testWS">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="testWSResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TestWebServiceWs">
    <wsdl:port binding="tns:TestWebServiceWsSoapBinding" name="TestWebServiceWsImplPort">
      <soap:address location="http://192.168.0.131:8082/soap/test"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>